asset_candidates =  [
# from S&P500
('A', 'Agilent Technologies, Inc.'),
('AAL', 'American Airlines Group Inc.'),
('AAP', 'Advance Auto Parts, Inc.'),
('AAPL', 'Apple Inc.'),
('ABBV', 'AbbVie Inc.'),
('ABC', 'AmerisourceBergen Corporation'),
('ABMD', 'Abiomed, Inc.'),
('ABT', 'Abbott Laboratories'),
('ACN', 'Accenture plc'),
('ADBE', 'Adobe Inc.'),
('ADI', 'Analog Devices, Inc.'),
('ADM', 'Archer-Daniels-Midland Company'),
('ADP', 'Automatic Data Processing, Inc.'),
('ADS', 'Alliance Data Systems Corporation'),
('ADSK', 'Autodesk, Inc.'),
('AEE', 'Ameren Corporation'),
('AEP', 'American Electric Power Company, Inc.'),
('AES', 'The AES Corporation'),
('AFL', 'Aflac Incorporated'),
('AGN', 'Algernon Pharmaceuticals Inc'), 
('AIG', 'American International Group, Inc.'),
('AIV', 'Apartment Investment and Management Company'),
('AIZ', 'Assurant, Inc.'),
('AJG', 'Arthur J. Gallagher & Co.'),
('AKAM', 'Akamai Technologies, Inc.'),
('ALB', 'Albemarle Corporation'),
('ALGN', 'Align Technology, Inc.'),
('ALK', 'Alaska Air Group, Inc.'),
('ALL', 'The Allstate Corporation'),
('ALLE', 'Allegion plc'),
('ALXN', 'Alexion Pharmaceuticals, Inc.'),
('AMAT', 'Applied Materials, Inc.'),
('AMCR', 'Amcor plc'),
('AMD', 'Advanced Micro Devices, Inc.'),
('AME', 'AMETEK, Inc.'),
('AMGN', 'Amgen Inc.'),
('AMP', 'Ameriprise Financial, Inc.'),
('AMT', 'American Tower Corporation (REIT)'),
('AMZN', 'Amazon.com, Inc.'),
('ANET', 'Arista Networks, Inc.'),
('ANSS', 'ANSYS, Inc.'),
('ANTM', 'Anthem, Inc.'),
('AON', 'Aon Plc'),
('AOS', 'A. O. Smith Corporation'),
('APA', 'Apache Corporation'),
('APD', 'Air Products and Chemicals, Inc.'),
('APH', 'Amphenol Corporation'),
('APTV', 'Aptiv PLC'),
('ARE', 'Alexandria Real Estate Equities, Inc.'),
('ARNC', 'Arconic Corporation'),
('ATO', 'Atmos Energy Corporation'),
('ATVI', 'Activision Blizzard, Inc.'),
('AVB', 'AvalonBay Communities, Inc.'),
('AVGO', 'Broadcom Inc.'),
('AVY', 'Avery Dennison Corporation'),
('AWK', 'American Water Works Company, Inc.'),
('AXP', 'American Express Company'),
('AZO', 'AutoZone, Inc.'),
('BA', 'The Boeing Company'),
('BAC', 'Bank of America Corporation'),
('BAX', 'Baxter International Inc.'),
('BBY', 'Best Buy Co., Inc.'),
('BDX', 'Becton, Dickinson and Company'),
('BEN', 'Franklin Resources, Inc.'),
('BF-B', 'Brown-Forman Corporation'),
('BIIB', 'Biogen Inc.'),
('BK', 'The Bank of New York Mellon Corporation'),
('BKNG', 'Booking Holdings Inc.'),
('BKR', 'Baker Hughes Company'),
('BLK', 'BlackRock, Inc.'),
('BLL', 'Ball Corporation'),
('BMY', 'Bristol-Myers Squibb Company'),
('BR', 'Broadridge Financial Solutions, Inc.'),
('BRK-B', 'Berkshire Hathaway Inc.'),
('BSX', 'Boston Scientific Corporation'),
('BWA', 'BorgWarner Inc.'),
('BXP', 'Boston Properties, Inc.'),
('C', 'Citigroup Inc.'),
('CAG', 'Conagra Brands, Inc.'),
('CAH', 'Cardinal Health, Inc.'),
('CAT', 'Caterpillar Inc.'),
('CB', 'Chubb Limited'),
('CBOE', 'Cboe Global Markets, Inc.'),
('CBRE', 'CBRE Group, Inc.'),
('CCI', 'Crown Castle International Corp. (REIT)'),
('CCL', 'Carnival Corporation & Plc'),
('CDNS', 'Cadence Design Systems, Inc.'),
('CDW', 'CDW Corporation'),
('CE', 'Celanese Corporation'),
('CERN', 'Cerner Corporation'),
('CF', 'CF Industries Holdings, Inc.'),
('CFG', 'Citizens Financial Group, Inc.'),
('CHD', 'Church & Dwight Co., Inc.'),
('CHRW', 'C.H. Robinson Worldwide, Inc.'),
('CHTR', 'Charter Communications, Inc.'),
('CI', 'Cigna Corporation'),
('CINF', 'Cincinnati Financial Corporation'),
('CL', 'Colgate-Palmolive Company'),
('CLX', 'The Clorox Company'),
('CMA', 'Comerica Incorporated'),
('CMCSA', 'Comcast Corporation'),
('CME', 'CME Group Inc.'),
('CMG', 'Chipotle Mexican Grill, Inc.'),
('CMI', 'Cummins Inc.'),
('CMS', 'CMS Energy Corporation'),
('CNC', 'Centene Corporation'),
('CNP', 'CenterPoint Energy, Inc.'),
('COF', 'Capital One Financial Corporation'),
('COG', 'Cabot Oil & Gas Corporation'),
('COO', 'The Cooper Companies, Inc.'),
('COP', 'ConocoPhillips'),
('COST', 'Costco Wholesale Corporation'),
('COTY', 'Coty Inc.'),
('CPB', 'Campbell Soup Company'),
('CPRI', 'Capri Holdings Limited'),
('CPRT', 'Copart, Inc.'),
('CRM', 'salesforce.com, inc.'),
('CSCO', 'Cisco Systems, Inc.'),
('CSX', 'CSX Corporation'),
('CTAS', 'Cintas Corporation'),
('CTL', 'CenturyLink, Inc.'),
('CTSH', 'Cognizant Technology Solutions Corporation'),
('CTVA', 'Corteva, Inc.'),
('CTXS', 'Citrix Systems, Inc.'),
('CVS', 'CVS Health Corporation'),
('CVX', 'Chevron Corporation'),
('CXO', 'Concho Resources Inc.'),
('D', 'Dominion Energy, Inc.'),
('DAL', 'Delta Air Lines, Inc.'),
('DD', 'DuPont de Nemours, Inc.'),
('DE', 'Deere & Company'),
('DFS', 'Discover Financial Services'),
('DG', 'Dollar General Corporation'),
('DGX', 'Quest Diagnostics Incorporated'),
('DHI', 'D.R. Horton, Inc.'),
('DHR', 'Danaher Corporation'),
('DIS', 'The Walt Disney Company'),
('DISCA', 'Discovery, Inc.'),
('DISCK', 'Discovery, Inc.'),
('DISH', 'DISH Network Corporation'),
('DLR', 'Digital Realty Trust, Inc.'),
('DLTR', 'Dollar Tree, Inc.'),
('DOV', 'Dover Corporation'),
('DOW', 'Dow Inc.'),
('DRE', 'Duke Realty Corporation'),
('DRI', 'Darden Restaurants, Inc.'),
('DTE', 'DTE Energy Company'),
('DUK', 'Duke Energy Corporation'),
('DVA', 'DaVita Inc.'),
('DVN', 'Devon Energy Corporation'),
('DXC', 'DXC Technology Company'),
('EA', 'Electronic Arts Inc.'),
('EBAY', 'eBay Inc.'),
('ECL', 'Ecolab Inc.'),
('ED', 'Consolidated Edison, Inc.'),
('EFX', 'Equifax Inc.'),
('EIX', 'Edison International'),
('EL', 'The Estee Lauder Companies Inc.'),
('EMN', 'Eastman Chemical Company'),
('EMR', 'Emerson Electric Co.'),
('EOG', 'EOG Resources, Inc.'),
('EQIX', 'Equinix, Inc. (REIT)'),
('EQR', 'Equity Residential'),
('ES', 'Eversource Energy'),
('ESS', 'Essex Property Trust, Inc.'),
('ETFC', 'E*TRADE Financial Corporation'),
('ETN', 'Eaton Corporation plc'),
('ETR', 'Entergy Corporation'),
('EVRG', 'Evergy, Inc.'),
('EW', 'Edwards Lifesciences Corporation'),
('EXC', 'Exelon Corporation'),
('EXPD', 'Expeditors International of Washington, Inc.'),
('EXPE', 'Expedia Group, Inc.'),
('EXR', 'Extra Space Storage Inc.'),
('F', 'Ford Motor Company'),
('FANG', 'Diamondback Energy, Inc.'),
('FAST', 'Fastenal Company'),
('FB', 'Facebook, Inc.'),
('FBHS', 'Fortune Brands Home & Security, Inc.'),
('FCX', 'Freeport-McMoRan Inc.'),
('FDX', 'FedEx Corporation'),
('FE', 'FirstEnergy Corp.'),
('FFIV', 'F5 Networks, Inc.'),
('FIS', 'Fidelity National Information Services, Inc.'),
('FISV', 'Fiserv, Inc.'),
('FITB', 'Fifth Third Bancorp'),
('FLIR', 'FLIR Systems, Inc.'),
('FLS', 'Flowserve Corporation'),
('FLT', 'FLEETCOR Technologies, Inc.'),
('FMC', 'FMC Corporation'),
('FOX', 'Fox Corporation'),
('FOXA', 'Fox Corporation'),
('FRC', 'First Republic Bank'),
('FRT', 'Federal Realty Investment Trust'),
('FTI', 'TechnipFMC plc'),
('FTNT', 'Fortinet, Inc.'),
('FTV', 'Fortive Corporation'),
('GD', 'General Dynamics Corporation'),
('GE', 'General Electric Company'),
('GILD', 'Gilead Sciences, Inc.'),
('GIS', 'General Mills, Inc.'),
('GL', 'Globe Life Inc.'),
('GLW', 'Corning Incorporated'),
('GM', 'General Motors Company'),
('GOOG', 'Alphabet Inc.'),
('GOOGL', 'Alphabet Inc.'),
('GPC', 'Genuine Parts Company'),
('GPN', 'Global Payments Inc.'),
('GPS', 'The Gap, Inc.'),
('GRMN', 'Garmin Ltd.'),
('GS', 'The Goldman Sachs Group, Inc.'),
('GWW', 'W.W. Grainger, Inc.'),
('HAL', 'Halliburton Company'),
('HAS', 'Hasbro, Inc.'),
('HBAN', 'Huntington Bancshares Incorporated'),
('HBI', 'Hanesbrands Inc.'),
('HCA', 'HCA Healthcare, Inc.'),
('HD', 'The Home Depot, Inc.'),
('HES', 'Hess Corporation'),
('HFC', 'HollyFrontier Corporation'),
('HIG', 'The Hartford Financial Services Group, Inc.'),
('HII', 'Huntington Ingalls Industries, Inc.'),
('HLT', 'Hilton Worldwide Holdings Inc.'),
('HOG', 'Harley-Davidson, Inc.'),
('HOLX', 'Hologic, Inc.'),
('HON', 'Honeywell International Inc.'),
('HP', 'Helmerich & Payne, Inc.'),
('HPE', 'Hewlett Packard Enterprise Company'),
('HPQ', 'HP Inc.'),
('HRB', 'H&R Block, Inc.'),
('HRL', 'Hormel Foods Corporation'),
('HSIC', 'Henry Schein, Inc.'),
('HST', 'Host Hotels & Resorts, Inc.'),
('HSY', 'The Hershey Company'),
('HUM', 'Humana Inc.'),
('IBM', 'International Business Machines Corporation'),
('ICE', 'Intercontinental Exchange, Inc.'),
('IDXX', 'IDEXX Laboratories, Inc.'),
('IEX', 'IDEX Corporation'),
('IFF', 'International Flavors & Fragrances Inc.'),
('ILMN', 'Illumina, Inc.'),
('INCY', 'Incyte Corporation'),
('INFO', 'IHS Markit Ltd.'),
('INTC', 'Intel Corporation'),
('INTU', 'Intuit Inc.'),
('IP', 'International Paper Company'),
('IPG', 'The Interpublic Group of Companies, Inc.'),
('IPGP', 'IPG Photonics Corporation'),
('IQV', 'IQVIA Holdings Inc.'),
('IR', 'Ingersoll Rand Inc.'),
('IRM', 'Iron Mountain Incorporated'),
('ISRG', 'Intuitive Surgical, Inc.'),
('IT', 'Gartner, Inc.'),
('ITW', 'Illinois Tool Works Inc.'),
('IVZ', 'Invesco Ltd.'),
('J', 'Jacobs Engineering Group Inc.'),
('JBHT', 'J.B. Hunt Transport Services, Inc.'),
('JCI', 'Johnson Controls International plc'),
('JKHY', 'Jack Henry & Associates, Inc.'),
('JNJ', 'Johnson & Johnson'),
('JNPR', 'Juniper Networks, Inc.'),
('JPM', 'JPMorgan Chase & Co.'),
('JWN', 'Nordstrom, Inc.'),
('K', 'Kellogg Company'),
('KEY', 'KeyCorp'),
('KEYS', 'Keysight Technologies, Inc.'),
('KHC', 'The Kraft Heinz Company'),
('KIM', 'Kimco Realty Corporation'),
('KLAC', 'KLA Corporation'),
('KMB', 'Kimberly-Clark Corporation'),
('KMI', 'Kinder Morgan, Inc.'),
('KMX', 'CarMax, Inc.'),
('KO', 'The Coca-Cola Company'),
('KR', 'The Kroger Co.'),
('KSS', "Kohl's Corporation"), 
('KSU', 'Kansas City Southern'),
('L', 'Loews Corporation'),
('LB', 'L Brands, Inc.'),
('LDOS', 'Leidos Holdings, Inc.'),
('LEG', 'Leggett & Platt, Incorporated'),
('LEN', 'Lennar Corporation'),
('LH', 'Laboratory Corporation of America Holdings'),
('LHX', 'L3Harris Technologies, Inc.'),
('LIN', 'Linde plc'),
('LKQ', 'LKQ Corporation'),
('LLY', 'Eli Lilly and Company'),
('LMT', 'Lockheed Martin Corporation'),
('LNC', 'Lincoln National Corporation'),
('LNT', 'Alliant Energy Corporation'),
('LOW', "Lowe's Companies, Inc."), 
('LRCX', 'Lam Research Corporation'),
('LUV', 'Southwest Airlines Co.'),
('LVS', 'Las Vegas Sands Corp.'),
('LW', 'Lamb Weston Holdings, Inc.'),
('LYB', 'LyondellBasell Industries N.V.'),
('LYV', 'Live Nation Entertainment, Inc.'),
('M', "Macy's, Inc."), 
('MA', 'Mastercard Incorporated'),
('MAA', 'Mid-America Apartment Communities, Inc.'),
('MAR', 'Marriott International, Inc.'),
('MAS', 'Masco Corporation'),
('MCD', "McDonald's Corporation"), 
('MCHP', 'Microchip Technology Incorporated'),
('MCK', 'McKesson Corporation'),
('MCO', "Moody's Corporation"), 
('MDLZ', 'Mondelez International, Inc.'),
('MDT', 'Medtronic plc'),
('MET', 'MetLife, Inc.'),
('MGM', 'MGM Resorts International'),
('MHK', 'Mohawk Industries, Inc.'),
('MKC', 'McCormick & Company, Incorporated'),
('MKTX', 'MarketAxess Holdings Inc.'),
('MLM', 'Martin Marietta Materials, Inc.'),
('MMC', 'Marsh & McLennan Companies, Inc.'),
('MMM', '3M Company'),
('MNST', 'Monster Beverage Corporation'),
('MO', 'Altria Group, Inc.'),
('MOS', 'The Mosaic Company'),
('MPC', 'Marathon Petroleum Corporation'),
('MRK', 'Merck & Co., Inc.'),
('MRO', 'Marathon Oil Corporation'),
('MS', 'Morgan Stanley'),
('MSCI', 'MSCI Inc.'),
('MSFT', 'Microsoft Corporation'),
('MSI', 'Motorola Solutions, Inc.'),
('MTB', 'M&T Bank Corporation'),
('MTD', 'Mettler-Toledo International Inc.'),
('MU', 'Micron Technology, Inc.'),
('MXIM', 'Maxim Integrated Products, Inc.'),
('MYL', 'Mylan, Inc.'),
('NBL', 'Noble Energy, Inc.'),
('NCLH', 'Norwegian Cruise Line Holdings Ltd.'),
('NDAQ', 'Nasdaq, Inc.'),
('NEE', 'NextEra Energy, Inc.'),
('NEM', 'Newmont Corporation'),
('NFLX', 'Netflix, Inc.'),
('NI', 'NiSource Inc.'),
('NKE', 'NIKE, Inc.'),
('NLOK', 'NortonLifeLock Inc.'),
('NLSN', 'Nielsen Holdings plc'),
('NOC', 'Northrop Grumman Corporation'),
('NOV', 'National Oilwell Varco, Inc.'),
('NOW', 'ServiceNow, Inc.'),
('NRG', 'NRG Energy, Inc.'),
('NSC', 'Norfolk Southern Corporation'),
('NTAP', 'NetApp, Inc.'),
('NTRS', 'Northern Trust Corporation'),
('NUE', 'Nucor Corporation'),
('NVDA', 'NVIDIA Corporation'),
('NVR', 'NVR, Inc.'),
('NWL', 'Newell Brands Inc.'),
('NWS', 'News Corporation'),
('NWSA', 'News Corporation'),
('O', 'Realty Income Corporation'),
('ODFL', 'Old Dominion Freight Line, Inc.'),
('OKE', 'ONEOK, Inc.'),
('OMC', 'Omnicom Group Inc.'),
('ORCL', 'Oracle Corporation'),
('ORLY', "O'Reilly Automotive, Inc."), 
('OXY', 'Occidental Petroleum Corporation'),
('PAYC', 'Paycom Software, Inc.'),
('PAYX', 'Paychex, Inc.'),
('PBCT', "People's United Financial, Inc."), 
('PCAR', 'PACCAR Inc'),
('PEAK', 'Healthpeak Properties, Inc.'),
('PEG', 'Public Service Enterprise Group Incorporated'),
('PEP', 'PepsiCo, Inc.'),
('PFE', 'Pfizer Inc.'),
('PFG', 'Principal Financial Group, Inc.'),
('PG', 'The Procter & Gamble Company'),
('PGR', 'The Progressive Corporation'),
('PH', 'Parker-Hannifin Corporation'),
('PHM', 'PulteGroup, Inc.'),
('PKG', 'Packaging Corporation of America'),
('PKI', 'PerkinElmer, Inc.'),
('PLD', 'Prologis, Inc.'),
('PM', 'Philip Morris International Inc.'),
('PNC', 'The PNC Financial Services Group, Inc.'),
('PNR', 'Pentair plc'),
('PNW', 'Pinnacle West Capital Corporation'),
('PPG', 'PPG Industries, Inc.'),
('PPL', 'PPL Corporation'),
('PRGO', 'Perrigo Company plc'),
('PRU', 'Prudential Financial, Inc.'),
('PSA', 'Public Storage'),
('PSX', 'Phillips 66'),
('PVH', 'PVH Corp.'),
('PWR', 'Quanta Services, Inc.'),
('PXD', 'Pioneer Natural Resources Company'),
('PYPL', 'PayPal Holdings, Inc.'),
('QCOM', 'QUALCOMM Incorporated'),
('QRVO', 'Qorvo, Inc.'),
('RCL', 'Royal Caribbean Cruises Ltd.'),
('RE', 'Everest Re Group, Ltd.'),
('REG', 'Regency Centers Corporation'),
('REGN', 'Regeneron Pharmaceuticals, Inc.'),
('RF', 'Regions Financial Corporation'),
('RHI', 'Robert Half International Inc.'),
('RJF', 'Raymond James Financial, Inc.'),
('RL', 'Ralph Lauren Corporation'),
('RMD', 'ResMed Inc.'),
('ROK', 'Rockwell Automation, Inc.'),
('ROL', 'Rollins, Inc.'),
('ROP', 'Roper Technologies, Inc.'),
('ROST', 'Ross Stores, Inc.'),
('RSG', 'Republic Services, Inc.'),
('RTX', 'Raytheon Technologies Corporation'),
('SBAC', 'SBA Communications Corporation (REIT)'),
('SBUX', 'Starbucks Corporation'),
('SCHW', 'The Charles Schwab Corporation'),
('SEE', 'Sealed Air Corporation'),
('SHW', 'The Sherwin-Williams Company'),
('SIVB', 'SVB Financial Group'),
('SJM', 'The J. M. Smucker Company'),
('SLB', 'Schlumberger Limited'),
('SLG', 'SL Green Realty Corp.'),
('SNA', 'Snap-on Incorporated'),
('SNPS', 'Synopsys, Inc.'),
('SO', 'The Southern Company'),
('SPG', 'Simon Property Group, Inc.'),
('SPGI', 'S&P Global Inc.'),
('SRE', 'Sempra Energy'),
('STE', 'STERIS plc'),
('STT', 'State Street Corporation'),
('STX', 'Seagate Technology plc'),
('STZ', 'Constellation Brands, Inc.'),
('SWK', 'Stanley Black & Decker, Inc.'),
('SWKS', 'Skyworks Solutions, Inc.'),
('SYF', 'Synchrony Financial'),
('SYK', 'Stryker Corporation'),
('SYY', 'Sysco Corporation'),
('T', 'AT&T Inc.'),
('TAP', 'Molson Coors Beverage Company'),
('TDG', 'TransDigm Group Incorporated'),
('TEL', 'TE Connectivity Ltd.'),
('TFC', 'Truist Financial Corporation'),
('TFX', 'Teleflex Incorporated'),
('TGT', 'Target Corporation'),
('TIF', 'Tiffany & Co.'),
('TJX', 'The TJX Companies, Inc.'),
('TMO', 'Thermo Fisher Scientific Inc.'),
('TMUS', 'T-Mobile US, Inc.'),
('TPR', 'Tapestry, Inc.'),
('TROW', 'T. Rowe Price Group, Inc.'),
('TRV', 'The Travelers Companies, Inc.'),
('TSCO', 'Tractor Supply Company'),
('TSN', 'Tyson Foods, Inc.'),
('TT', 'Trane Technologies plc'),
('TTWO', 'Take-Two Interactive Software, Inc.'),
('TWTR', 'Twitter, Inc.'),
('TXN', 'Texas Instruments Incorporated'),
('TXT', 'Textron Inc.'),
('UA', 'Under Armour, Inc.'),
('UAA', 'Under Armour, Inc.'),
('UAL', 'United Airlines Holdings, Inc.'),
('UDR', 'UDR, Inc.'),
('UHS', 'Universal Health Services, Inc.'),
('ULTA', 'Ulta Beauty, Inc.'),
('UNH', 'UnitedHealth Group Incorporated'),
('UNM', 'Unum Group'),
('UNP', 'Union Pacific Corporation'),
('UPS', 'United Parcel Service, Inc.'),
('URI', 'United Rentals, Inc.'),
('USB', 'U.S. Bancorp'),
('V', 'Visa Inc.'),
('VAR', 'Varian Medical Systems, Inc.'),
('VFC', 'V.F. Corporation'),
('VIAC', 'ViacomCBS Inc.'),
('VLO', 'Valero Energy Corporation'),
('VMC', 'Vulcan Materials Company'),
('VNO', 'Vornado Realty Trust'),
('VRSK', 'Verisk Analytics, Inc.'),
('VRSN', 'VeriSign, Inc.'),
('VRTX', 'Vertex Pharmaceuticals Incorporated'),
('VTR', 'Ventas, Inc.'),
('VZ', 'Verizon Communications Inc.'),
('WAB', 'Wabtec Corporation'),
('WAT', 'Waters Corporation'),
('WBA', 'Walgreens Boots Alliance, Inc.'),
('WDC', 'Western Digital Corporation'),
('WEC', 'WEC Energy Group, Inc.'),
('WELL', 'Welltower Inc.'),
('WFC', 'Wells Fargo & Company'),
('WHR', 'Whirlpool Corporation'),
('WLTW', 'Willis Towers Watson Public Limited Company'),
('WM', 'Waste Management, Inc.'),
('WMB', 'The Williams Companies, Inc.'),
('WMT', 'Walmart Inc.'),
('WRB', 'W. R. Berkley Corporation'),
('WRK', 'WestRock Company'),
('WU', 'The Western Union Company'),
('WY', 'Weyerhaeuser Company'),
('WYNN', 'Wynn Resorts, Limited'),
('XEL', 'Xcel Energy Inc.'),
('XLNX', 'Xilinx, Inc.'),
('XOM', 'Exxon Mobil Corporation'),
('XRAY', 'DENTSPLY SIRONA Inc.'),
('XRX', 'Xerox Holdings Corporation'),
('XYL', 'Xylem Inc.'),
('YUM', 'Yum! Brands, Inc.'),
('ZBH', 'Zimmer Biomet Holdings, Inc.'),
('ZBRA', 'Zebra Technologies Corporation'),
('ZION', 'Zions Bancorporation, National Association'),
('ZTS', 'Zoetis Inc.'),
# from TradingValley, no data yet
('BIV', 'Vanguard Intermediate-Term Bond Index Fund ETF Shares'),
('LQD', 'iShares iBoxx $ Investment Grade Corporate Bond ETF'),
('MUB', 'iShares National Muni Bond ETF'),
('TLT', 'iShares 20+ Year Treasury Bond ETF'),
('VB',  'Vanguard Small-Cap Index Fund ETF Shares'),
('VNQ', 'Vanguard Real Estate Index Fund ETF Shares'),
('VOO', 'Vanguard S&P 500 ETF'),
('VEA', 'Vanguard FTSE Developed Markets Index Fund ETF Shares'),
('VWO', 'Vanguard FTSE Emerging Markets Index Fund ETF Shares'),
('IAU', 'iShares Gold Trust'),
# 0050.TW constituents
('1101.TW', '台泥'),
('1102.TW', '亞泥'),
('1216.TW', '統一'),
('1301.TW', '台塑'),
('1303.TW', '南亞'),
('1326.TW', '台化'),
('1402.TW', '遠東新'),
('2002.TW', '中鋼'),
('2105.TW', '正新'),
('2207.TW', '和泰車'),
('2227.TW', '裕日車'),
('2301.TW', '光寶科'),
('2303.TW', '聯電'),
('2308.TW', '台達電'),
('2317.TW', '鴻海'),
('2327.TW', '國巨'),
('2330.TW', '台積電'),
('2352.TW', '佳世達'),
('2357.TW', '華碩'),
('2382.TW', '廣達'),
('2395.TW', '研華'),
('2408.TW', '南亞科'),
('2412.TW', '中華電'),
('2454.TW', '聯發科'),
('2474.TW', '可成'),
('2609.TW', '陽明'),
('2610.TW', '華航'),
('2633.TW', '台灣高鐵'), 
('2801.TW', '彰銀'),
('2823.TW', '中壽'),
('2880.TW', '華南金'),
('2881.TW', '富邦金'),
('2882.TW', '國泰金'),
('2883.TW', '開發金'),
('2884.TW', '玉山金'),
('2885.TW', '元大金'),
('2886.TW', '兆豐金'),
('2887.TW', '台新金'),
('2888.TW', '新光金'),
('2890.TW', '永豐金'),
('2891.TW', '中信金'),
('2892.TW', '第一金'),
('2912.TW', '統一超'),
('3008.TW', '大立光'),
('3045.TW', '台灣大'),
('3711.TW', '日月光投控'), 
('4904.TW', '遠傳'),
('4938.TW', '和碩'),
('5871.TW', '中租-KY'),
('5876.TW', '上海商銀'), 
('5880.TW', '合庫金'),
('6505.TW', '台塑化'),
('6669.TW', '緯穎'),
('9910.TW', '豐泰'),
('0050.TW', '元大台灣50'),
# Crypto
('BTC-USD', 'Bitcoin 比特幣'),
('ETH-USD', 'Ethereum 乙太幣'),
# 劭偉、正威競賽用
('00720B.TW', '元大投資級公司債'),
('00725B.TW', '國泰投資級公司債'),
('00740B.TW', '富邦全球投等債'),
('00751B.TW', '元大AAA至A公司債'),
('00862B.TW', '中信投資級公司債'),
('5274.TW', '信驊'),
('6274.TW', '台燿'),
('6470.TW', '宇智'),
('3491.TW', '昇達科'),
('3105.TW', '穩懋'),
('5439.TW', '高技'),
('XAU', 'Gold per ounce / US Dollar Spot'),
# Ark Investment Management ETFs
('ARKF', 'ARK Fintech Innovation ETF'), 
('ARKG', 'ARK Genomic Revolution ETF'), 
('ARKK', 'ARK Innovation ETF'), 
('ARKQ', 'ARK Autonomous Technology & Robotics ETF'), 
('ARKW', 'ARK Next Generation Internet ETF'),
# 2021-01-29 18:54
('SPY', 'SPDR S&P 500 Trust ETF'),
('IEF', 'iShares 7-10 Year Treasury Bond ETF')
]
